auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.create_auction, name="create"),
    path("active", views.active_listings, name="active"),
    path("auction/<int:listing_id>", views.auction, name="auction"),
    path("categories", views.categories, name="categories"),
    path("category/<int:category_id>", views.category, name="category"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("place_bid/<int:listing_id>", views.place_bid, name="place_bid"),
    path("close/<int:listing_id>", views.close, name="close"),
    path("comment/<int:listing_id>", views.comment, name="comment"),
]

commerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path("admin/", admin.site.urls), path("", include("auctions.urls"))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from enum import unique

from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass


class Category(models.Model):
    title = models.CharField(max_length=200)

    def __str__(self):
        return f"title: {self.title}"


class Listing(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    starting_price = models.FloatField(max_length=6)
    photo_url = models.URLField(blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="auctions")
    active = models.BooleanField(blank=True, default=True)
    winner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="purchases", blank=True, null=True
    )
    category = models.ManyToManyField(Category, related_name="listings")

    def __str__(self):
        return f"title: {self.title}<br>description: {self.description}<br>starting_price: {self.starting_price}<br>photo_url: {self.photo_url}<br>owner: {self.owner}<br>active: {self.active}<br>winner: {self.winner}"


class Photo(models.Model):
    name = models.CharField(max_length=200)
    img = models.ImageField(upload_to="photos/")
    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, related_name="photos"
    )
    position = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f"name: {self.name}<br>path: {self.img}<br>listing: {self.listing.pk}<br>position: {self.position}"


class Bid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bids")
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="bids")
    amount = models.FloatField(max_length=6)

    def __str__(self):
        return f"user: {self.user}<br>listing: {self.listing}<br>amount: {self.amount}"


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, related_name="comments"
    )
    created = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __str__(self):
        return f"user: {self.user}<br>listing: {self.listing}<br>created: {self.created}<br>content: {self.content}"


class Watchlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="watched")
    auction = models.ForeignKey(
        Listing, on_delete=models.CASCADE, related_name="watched"
    )

    def __str__(self):
        return f"user: {self.user}<br>listing: {self.auction}"

auctions/views.py
from django.contrib.auth import authenticate, login, logout, decorators
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import User, Category, Listing, Photo, Bid, Comment, Watchlist


def index(request):
    return active_listings(request)


def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(
                request,
                "auctions/login.html",
                {"title": "Login", "message": "Invalid username and/or password."},
            )
    else:
        return render(request, "auctions/login.html", {"title": "Log In"})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(
                request,
                "auctions/register.html",
                {"title": "Register", "message": "Passwords must match."},
            )

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(
                request,
                "auctions/register.html",
                {"title": "Register", "message": "Username already taken."},
            )
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(
            request,
            "auctions/register.html",
            {
                "title": "Register",
            },
        )


@decorators.login_required(login_url="auctions:login")
def create_auction(request):
    if "title" and "description" and "starting_bid" not in request.POST:
        return render(
            request,
            "auctions/create.html",
            {"title": "Create Listing", "categories": Category.objects.all()},
        )
    else:
        title = request.POST["title"] or ""
        description = request.POST["description"] or ""
        starting_bid = request.POST["starting_bid"] or ""
        owner = User.objects.get(pk=request.user.id)
        listing = Listing(
            title=title,
            description=description,
            starting_price=starting_bid,
            owner=owner,
            active=True,
        )
        listing.save()

        selected_categories = request.POST.getlist("category_list")
        for category_title in selected_categories:
            category = Category.objects.get(title=category_title)
            listing.category.add(category)

        if "image" in request.FILES:
            image_file = request.FILES["image"]
            Photo.objects.create(name=image_file.name, img=image_file, listing=listing)

        return HttpResponseRedirect(reverse("auctions:index"))


def active_listings(request):
    auctions_list = Listing.objects.filter(active=True)
    return render(
        request,
        "auctions/auctions.html",
        {"title": "Active Listings", "auctions_list": auctions_list},
    )


def auction(request, listing_id, message=""):
    auction = Listing.objects.get(pk=listing_id)
    bid = auction.bids.filter(listing_id=listing_id)  # type: ignore
    current_bid = (
        (
            auction.bids.filter(listing_id=listing_id)  # type: ignore
            .order_by("-amount")
            .first()
            .amount
        )
        if bid.exists()
        else None
    )
    is_watched = auction.watched.filter(  # type: ignore
        user_id=request.user.id, auction_id=listing_id
    ).exists()

    if "watch" in request.POST:
        if not Watchlist.objects.filter(
            user_id=request.user.id, auction_id=request.POST["watch"]
        ).exists():
            watchlist_user = User.objects.get(pk=request.user.id)
            watchlist_auction = Listing.objects.get(pk=request.POST["watch"])
            watched_auction = Watchlist(user=watchlist_user, auction=watchlist_auction)
            watched_auction.save()
    elif "unwatch" in request.POST:
        Watchlist.objects.get(
            user_id=request.user.id, auction_id=request.POST["unwatch"]
        ).delete()

    is_watched = auction.watched.filter(  # type: ignore
        user_id=request.user.id, auction_id=listing_id
    ).exists()

    comments = Comment.objects.filter(listing_id=listing_id).all().order_by("created")

    return render(
        request,
        "auctions/auction.html",
        {
            "title": "Auction Details",
            "auction": auction,
            "is_watched": is_watched,
            "current_bid": current_bid,
            "message": message,
            "comments": comments,
        },
    )


def categories(request):
    categories = Category.objects.all()

    return render(
        request,
        "auctions/categories.html",
        {"title": "Categories", "categories": categories},
    )


def category(request, category_id):
    category = Category.objects.get(pk=category_id)
    auctions_list = category.listings.filter(active=True)  # type: ignore
    return render(
        request,
        "auctions/auctions.html",
        {"title": category.title, "auctions_list": auctions_list},
    )


@decorators.login_required(login_url="auctions:login")
def watchlist(request):
    watched = User.objects.get(pk=request.user.id).watched.all()  # type: ignore
    auctions_list = [entry.auction for entry in watched]

    return render(
        request,
        "auctions/auctions.html",
        {"title": "Watchlist", "auctions_list": auctions_list},
    )


@decorators.login_required(login_url="auctions:login")
def place_bid(request, listing_id):
    listing = Listing.objects.get(pk=listing_id)
    message = ""
    if listing.owner.id == request.user.id:
        message = "You cannot bid on your own auction."
    else:
        if "bid_amount" in request.POST:
            bid_amount = request.POST["bid_amount"]
            if listing.bids.exists():  # type: ignore
                highest_bid = listing.bids.all().order_by("-amount").first()  # type: ignore
                if float(bid_amount) > highest_bid.amount:
                    if highest_bid.user.id != request.user.id:  # type: ignore
                        bid_user = User.objects.get(pk=request.user.id)
                        bid_auction = Listing.objects.get(pk=listing_id)
                        bid = Bid(user=bid_user, listing=bid_auction, amount=bid_amount)
                        bid.save()
                    else:
                        message = "You are already the highest bidder."
                else:
                    message = "Your bid must be higher than the current bid."
            elif float(bid_amount) > listing.starting_price:
                bid_user = User.objects.get(pk=request.user.id)
                bid_auction = Listing.objects.get(pk=listing_id)
                bid = Bid(user=bid_user, listing=bid_auction, amount=bid_amount)
                bid.save()
            else:
                message = "Your bid must be higher than the starting price."
    return auction(request, listing_id, message)


@decorators.login_required(login_url="auctions:login")
def close(request, listing_id):
    listing = Listing.objects.get(id=listing_id)
    highest_bidder = listing.bids.all().order_by("-amount").first()  # type: ignore
    if highest_bidder:
        listing.winner = highest_bidder.user
        listing.active = False
        listing.save()
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        message = "There are no bids for this auction yer."
        return auction(request, listing_id, message)


@decorators.login_required(login_url="auctions:login")
def comment(request, listing_id):
    content = request.POST["comment"]
    comment_exists = Comment.objects.filter(
        user_id=request.user.id, content=content
    ).exists()
    if not comment_exists:
        Comment(
            user=User.objects.get(pk=request.user.id),
            listing=Listing.objects.get(pk=listing_id),
            content=request.POST["comment"],
        ).save()
    return auction(request, listing_id)

auctions/templates/auctions/active.html
{% extends "auctions/layout.html" %}
{% block title %}{{ title }}{% endblock %}
{% block body %}
    <h2>{{ title }}</h2>
    {% for auction in active_auctions %}
        <div class="card mb-3"
             onclick="location.href='{% url 'auctions:auction' auction.pk %}'"
             style="cursor: pointer">
            <div class="row g-0">
                {% if auction.photos.all %}
                    <div class="col-md-4">
                        <img src="{{ auction.photos.first.img.url }}"
                             alt="{{ auction.photos.first.name }}"
                             class="img-fluid rounded-start">
                    </div>
                {% endif %}
                <div class="col-md-8">
                    <div class="card-body d-flex align-items-start flex-column"
                         style="height: 100%">
                        <h5 class="card-title">{{ auction.title }}</h5>
                        <p class="card-text">{{ auction.description }}</p>
                        {% if auction.category.all %}
                            <div class="btn-group mb-3">
                                {% for category in auction.category.all %}
                                    <a href="{% url 'auctions:category' category.pk %}"
                                       class="btn btn-outline-secondary">{{ category.title }}</a>
                                {% endfor %}
                            </div>
                        {% endif %}
                        <div class="alert alert-primary mt-auto" role="alert">Price: {{ auction.starting_price }} $</div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

auctions/templates/auctions/auction.html
{% extends "auctions/layout.html" %}
{% block title %}{{ title }}{% endblock %}
{% block body %}
    {% if message %}<div class="alert alert-danger" role="alert">{{ message }}</div>{% endif %}
    {% if user.is_authenticated and auction.winner.id and auction.winner.id == user.id %}
        <div class="alert alert-primary">
            Congratulations {{ user.name }}! You won this auction with a bid of
            <strong>${{ current_bid }}</strong>
        </div>
    {% endif %}
    <div class="card mb-5">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{{ auction.photos.first.img.url }}"
                     alt="{{ auction.photos.first.name }}"
                     class="img-fluid rounded-start">
            </div>
            <div class="col-md-8">
                <div class="card-body d-flex align-items-start flex-column"
                     style="height: 100%">
                    <h5 class="card-title  d-flex justify-content-end flex-row"
                        style="width: 100%;
                               gap: 20px">
                        <div style="margin-right: auto;">{{ auction.title }}</div>
                        {% if auction.active == True and user.is_authenticated and auction.owner.id == user.id %}
                            <form action="{% url "auctions:close" auction.pk %}"
                                  method="post"
                                  style="display: inline">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">
                                    <i class="bi bi-hammer"></i>
                                </button>
                            </form>
                        {% endif %}
                        <form action="{% url "auctions:auction" auction.pk %}"
                              method="post"
                              style="display: inline">
                            {% csrf_token %}
                            <input type="hidden"
                                   name="{% if is_watched %}unwatch{% else %}watch{% endif %}"
                                   value="{{ auction.pk }}">
                            {% if user.is_authenticated %}
                                <button type="submin"
                                        class="btn {% if is_watched %} btn-primary {% else %} btn-outline-primary {% endif %}">
                                    <i class="bi {% if is_watched %} bi-eye-fill {% else %} bi-eye {% endif %}"></i>
                                </button>
                            {% else %}
                                <button type="submin" class="btn btn-secondary" disabled>
                                    <i class="bi bi-eye-fill"></i>
                                </button>
                            {% endif %}
                        </form>
                    </h5>
                    {% if auction.category.all %}
                        <div class="btn-group mb-3">
                            {% for category in auction.category.all %}
                                <a href="{% url 'auctions:category' category.pk %}"
                                   class="btn btn-outline-secondary">{{ category.title }}</a>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <p class="card-text">{{ auction.description }}</p>
                    <p class="card-text">
                        <small class="text-muted text-capitalize">Owner: {{ auction.owner }}</small>
                    </p>
                    {% if auction.winner %}
                        <p class="card-text">
                            <small class="text-muted text-capitalize">Winner: {{ auction.winner }}</small>
                        </p>
                    {% endif %}
                    <div class="mt-auto d-flex justify-content-start flex-row"
                         style="width:100%;
                                gap: 20px">
                        {% with auction.bids.all|dictsortreversed:"amount"|first as highest_bid %}
                            <div class="alert alert-primary m-0" role="alert">
                                Price
                                {% if highest_bid %}
                                    ${{ highest_bid.amount }}
                                {% else %}
                                    ${{ auction.starting_price }}
                                {% endif %}
                            </div>
                            {% if not auction.winner and highest_bid.user.id == user.id %}
                                <div class="alert alert-light m-0" role="alert" style="gap: 5px">
                                    <i class="bi bi-info-circle-fill"></i>
                                    <span>You are the highest bidder!</span>
                                </div>
                            {% endif %}
                        {% endwith %}
                        {% if user.is_authenticated %}
                            <form action="{% url 'auctions:place_bid' auction.pk %}"
                                  method="post"
                                  class="d-flex justify-content-end flex-row"
                                  style="gap: 20px;
                                         margin-left: auto">
                                {% csrf_token %}
                                <div class="input-group">
                                    <span class="input-group-text">Bid</span>
                                    <input type="number"
                                           class="form-control"
                                           name="bid_amount"
                                           min="0.00"
                                           step="0.01"
                                           placeholder="0.00"
                                           required>
                                    <span class="input-group-text">$</span>
                                </div>
                                <button type="submit" class="btn btn-primary" style="white-space: nowrap;">Place Bid</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% for comment in comments %}
        <div class="card mb-3">
            <div class="card-body">
                <p class="card-text">{{ comment.content }}</p>
                <p class="card-text">
                    <small class="text-muted text-capitalize">User: {{ comment.user }}</small>
                </p>
            </div>
        </div>
    {% endfor %}
    {% if user.is_authenticated %}
        <form action="{% url 'auctions:comment' auction.pk %}"
              method="post"
              {% if comments %}class="mt-5"{% endif %}>
            {% csrf_token %}
            <div class="input-group mb-3">
                <span class="input-group-text">Comment</span>
                <textarea name="comment"
                          id="comment"
                          class="form-control"
                          required
                          placeholder="Share your thoughts about this auction..."></textarea>
            </div>
            <button type="submit" class="btn btn-primary ml-auto">Submit Comment</button>
        </form>
    {% endif %}
{% endblock %}

auctions/templates/auctions/auctions.html
{% extends "auctions/layout.html" %}
{% block title %}{{ title }}{% endblock %}
{% block body %}
    {% for auction in auctions_list %}
        <div class="card mb-3"
             onclick="location.href='{% url 'auctions:auction' auction.pk %}'"
             style="cursor: pointer">
            <div class="row g-0">
                {% if auction.photos.all %}
                    <div class="col-md-4">
                        <img src="{{ auction.photos.first.img.url }}"
                             alt="{{ auction.photos.first.name }}"
                             class="img-fluid rounded-start">
                    </div>
                {% endif %}
                <div class="col-md-8">
                    <div class="card-body d-flex align-items-start flex-column"
                         style="height: 100%">
                        <h5 class="card-title">{{ auction.title }}</h5>
                        <p class="card-text">{{ auction.description }}</p>
                        {% if auction.category.all %}
                            <div class="btn-group mb-3">
                                {% for category in auction.category.all %}
                                    <a href="{% url 'auctions:category' category.pk %}"
                                       class="btn btn-outline-secondary">{{ category.title }}</a>
                                {% endfor %}
                            </div>
                        {% endif %}
                        {% with auction.bids.all|dictsortreversed:"amount"|first as highest_bid %}
                            <div class="alert alert-primary mt-auto" role="alert">
                                Price
                                {% if highest_bid %}
                                    ${{ highest_bid.amount }}
                                {% else %}
                                    ${{ auction.starting_price }}
                                {% endif %}
                            </div>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}
{% block title %}{{ title }}{% endblock %}
{% block body %}
    <ul class="list-group list-group-flush">
        {% for category in categories %}
            <li class="list-group-item">
                <a href="{% url 'auctions:category' category.pk %}">{{ category.title }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}
{% block title %}{{ title }}{% endblock %}
{% block body %}
    <form action="{% url "auctions:create" %}"
          method="post"
          enctype="multipart/form-data">
        {% csrf_token %}
        <div class="input-group mb-3">
            <span class="input-group-text">Title</span>
            <input type="text"
                   class="form-control"
                   name="title"
                   placeholder="Auction Title"
                   required>
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text">Description</span>
            <textarea class="form-control" name="description" id="description" required></textarea>
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text">Upload Image</span>
            <input type="file" class="form-control" name="image" id="image">
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text">Starting Bid</span>
            <input type="number"
                   class="form-control"
                   name="starting_bid"
                   min="0.00"
                   step="0.01"
                   placeholder="0.00"
                   required>
            <span class="input-group-text">$</span>
        </div>
        <div class="input-group mb-3">
            <label for="category_list" class="input-group-text">Categories</label>
            <select name="category_list" id="category_list" class="form-select" multiple>
                {% for category in categories %}<option value="{{ category.title }}">{{ category.title }}</option>{% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Create Auction</button>
    </form>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
    <head>
        <title>
            {% block title %}Auctions{% endblock %}
        </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT"
              crossorigin="anonymous">
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <ul class="nav nav-pills mt-3">
            <li class="nav-item px-2">
                <a class="nav-link {% if title == 'Active Listings' %}active{% endif %}"
                   href="{% url 'auctions:active' %}">Active Listings</a>
            </li>
            <li class="nav-item px-2">
                <a class="nav-link {% if title == 'Categories' %}active{% endif %}"
                   href="{% url 'auctions:categories' %}">Categories</a>
            </li>
            <li class="nav-item px-2">
                <a class="nav-link position-relative {% if title == 'Watchlist' %}active{% endif %} {% if not user.is_authenticated %}disabled{% endif %}"
                   href="{% url 'auctions:watchlist' %}">Watchlist
                    {% if user.watched.count %}<span class="badge bg-danger">{{ user.watched.count }}</span>{% endif %}
                </a>
            </li>
            <li class="nav-item px-2">
                <a class="nav-link {% if title == 'Create Listing' %}active{% endif %} {% if not user.is_authenticated %}disabled{% endif %}"
                   href="{% url 'auctions:create' %}">Create Listing</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item px-2">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item px-2">
                    <a class="nav-link {% if title == 'Log In' %}active{% endif %}"
                       href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item px-2">
                    <a class="nav-link {% if title == 'Register' %}active{% endif %}"
                       href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
            <li class="nav-item px-2" style="margin-left: auto;">
                <span href="#" class="nav-link" style="color: var(--bs-heading-color);">
                    {% if user.is_authenticated %}
                        <i class="bi bi-person-fill"></i> <strong class="text-capitalize">{{ user.username }}</strong>
                    {% else %}
                        Not signed in
                    {% endif %}
                </span>
            </li>
        </ul>
        <hr>
        {% block body %}{% endblock %}
    </body>
</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}
{% block body %}
    {% if message %}<div>{{ message }}</div>{% endif %}
    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
            <span class="input-group-text">Username</span>
            <input autofocus class="form-control" type="text" name="username">
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text">Password</span>
            <input class="form-control" type="password" name="password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>
    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>
{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}
{% block body %}
    {% if message %}<div>{{ message }}</div>{% endif %}
    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
            <span class="input-group-text">Username</span>
            <input class="form-control" autofocus type="text" name="username">
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text">Email Address</span>
            <input class="form-control" type="email" name="email">
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text">Password</span>
            <input class="form-control" type="password" name="password">
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text">Confirm Password</span>
            <input class="form-control" type="password" name="confirmation">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>
    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>
{% endblock %}